# Generated by Django 4.2.3 on 2023-07-20 03:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='listing name')),
                ('starting_bid', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='starting bid')),
                ('image_url', models.URLField(max_length=256, verbose_name='image url')),
                ('description', models.TextField(verbose_name='listing description')),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='lister name')),
            ],
            options={
                'verbose_name': 'listing',
                'verbose_name_plural': 'listings',
            },
        ),
    ]
